
services:
  db:
    image: postgres:16-alpine
    container_name: meduzzen_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: meduzzen_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: meduzzen_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/meduzzen_db
      # SECRET, adjust in production
      JWT_SECRET: your-secret-key-here-change-in-production
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - uploads:/app/uploads

  frontend:
    image: node:20-alpine
    container_name: meduzzen_frontend
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: sh -c "npm ci || npm install && npm start"
    environment:
      - CI=false
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
  uploads:


